// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptContactRequest = `-- name: AcceptContactRequest :one
WITH accepted AS (
    UPDATE contact_requests
    SET status = 'accepted', updated_at = now()
    WHERE id = $1
      AND recipient_id = $2
      AND status = 'pending'
    RETURNING sender_id, recipient_id
), inserted AS (
    INSERT INTO contacts (user1, user2)
    SELECT
        LEAST(sender_id, recipient_id),
        GREATEST(sender_id, recipient_id)
    FROM accepted
    ON CONFLICT DO NOTHING
)
SELECT EXISTS(SELECT 1 FROM accepted) AS accepted
`

type AcceptContactRequestParams struct {
	RequestID   pgtype.UUID
	RecipientID pgtype.UUID
}

func (q *Queries) AcceptContactRequest(ctx context.Context, arg AcceptContactRequestParams) (bool, error) {
	row := q.db.QueryRow(ctx, acceptContactRequest, arg.RequestID, arg.RecipientID)
	var accepted bool
	err := row.Scan(&accepted)
	return accepted, err
}

const cancelContactRequest = `-- name: CancelContactRequest :one
UPDATE contact_requests
SET status = 'cancelled', updated_at = now()
WHERE id = $1
  AND sender_id = $2
  AND status = 'pending'
RETURNING id
`

type CancelContactRequestParams struct {
	RequestID pgtype.UUID
	SenderID  pgtype.UUID
}

func (q *Queries) CancelContactRequest(ctx context.Context, arg CancelContactRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, cancelContactRequest, arg.RequestID, arg.SenderID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const declineContactRequest = `-- name: DeclineContactRequest :one
UPDATE contact_requests
SET status = 'declined', updated_at = now()
WHERE id = $1
  AND recipient_id = $2
  AND status = 'pending'
RETURNING id
`

type DeclineContactRequestParams struct {
	RequestID   pgtype.UUID
	RecipientID pgtype.UUID
}

func (q *Queries) DeclineContactRequest(ctx context.Context, arg DeclineContactRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, declineContactRequest, arg.RequestID, arg.RecipientID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const sendContactRequest = `-- name: SendContactRequest :one
INSERT INTO contact_requests (sender_id, recipient_id)
SELECT $1, id
FROM users
WHERE username = $2
RETURNING id
`

type SendContactRequestParams struct {
	SenderID pgtype.UUID
	Username string
}

func (q *Queries) SendContactRequest(ctx context.Context, arg SendContactRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, sendContactRequest, arg.SenderID, arg.Username)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
