// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const getConversationsForUser = `-- name: GetConversationsForUser :many
SELECT c.id, c.name, c.created_by, c.last_message_sequence, c.created_at, c.updated_at
FROM conversations c
INNER JOIN conversation_participants cp
    ON c.id = cp.conversation_id
WHERE cp.user_id = $1
`

func (q *Queries) GetConversationsForUser(ctx context.Context, userID pgtype.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, getConversationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.LastMessageSequence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertConversation = `-- name: InsertConversation :one
INSERT INTO conversations (name, created_by)
VALUES ($1, $2)
RETURNING id, name, created_by, last_message_sequence, created_at, updated_at
`

type InsertConversationParams struct {
	Name      pgtype.Text
	CreatedBy pgtype.UUID
}

func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, insertConversation, arg.Name, arg.CreatedBy)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.LastMessageSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConversationParticipant = `-- name: InsertConversationParticipant :one
INSERT INTO conversation_participants (conversation_id, user_id)
SELECT $1, $2
WHERE EXISTS (
    SELECT 1
    FROM conversations
    WHERE id = $1
        AND created_by = $3
)
RETURNING conversation_id, user_id, created_at, updated_at
`

type InsertConversationParticipantParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
	CreatedBy      pgtype.UUID
}

func (q *Queries) InsertConversationParticipant(ctx context.Context, arg InsertConversationParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, insertConversationParticipant, arg.ConversationID, arg.UserID, arg.CreatedBy)
	var i ConversationParticipant
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextMessageSequence = `-- name: NextMessageSequence :one
UPDATE conversations
SET last_message_sequence = last_message_sequence + 1
WHERE id = $1
RETURNING last_message_sequence
`

func (q *Queries) NextMessageSequence(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextMessageSequence, id)
	var last_message_sequence int64
	err := row.Scan(&last_message_sequence)
	return last_message_sequence, err
}

const updateConversationName = `-- name: UpdateConversationName :one
UPDATE conversations
SET name = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, created_by, last_message_sequence, created_at, updated_at
`

type UpdateConversationNameParams struct {
	Name pgtype.Text
	ID   pgtype.UUID
}

func (q *Queries) UpdateConversationName(ctx context.Context, arg UpdateConversationNameParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationName, arg.Name, arg.ID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.LastMessageSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
