// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events_outbox.sql

package db

import (
	"context"
)

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, event_type, subject, payload
FROM events_outbox
WHERE published_at IS NULL
ORDER BY created_at, id
LIMIT $1
`

type GetPendingOutboxEventsRow struct {
	ID        int64
	EventType string
	Subject   string
	Payload   []byte
}

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]GetPendingOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingOutboxEventsRow
	for rows.Next() {
		var i GetPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Subject,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO events_outbox (
    event_type,
    subject,
    payload
)
VALUES ($1, $2, $3)
`

type InsertOutboxEventParams struct {
	EventType string
	Subject   string
	Payload   []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.EventType, arg.Subject, arg.Payload)
	return err
}

const markPublishedOutboxEvents = `-- name: MarkPublishedOutboxEvents :execrows
UPDATE events_outbox
SET published_at = now()
WHERE id = ANY($1::bigint[]) AND published_at IS NULL
`

func (q *Queries) MarkPublishedOutboxEvents(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.db.Exec(ctx, markPublishedOutboxEvents, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
