// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
    conversation_id,
    message_sequence,
    sender_id,
    body,
    client_message_id
)
SELECT $1, $2, $3, $4, $5
WHERE EXISTS (
    SELECT 1
    FROM conversation_participants
    WHERE conversation_id = $1 AND user_id = $3
)
RETURNING id, conversation_id, sender_id, client_message_id, message_sequence, body, created_at, updated_at
`

type InsertMessageParams struct {
	ConversationID  pgtype.UUID
	MessageSequence int64
	SenderID        pgtype.UUID
	Body            string
	ClientMessageID pgtype.UUID
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ConversationID,
		arg.MessageSequence,
		arg.SenderID,
		arg.Body,
		arg.ClientMessageID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.ClientMessageID,
		&i.MessageSequence,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const syncMessages = `-- name: SyncMessages :many
SELECT m.id, m.conversation_id, m.sender_id, m.client_message_id, m.message_sequence, m.body, m.created_at, m.updated_at
FROM messages m
INNER JOIN conversation_participants cp
    ON cp.conversation_id = m.conversation_id
        AND cp.user_id = $1
WHERE m.conversation_id = $2
    AND message_sequence > $3
ORDER BY m.message_sequence DESC
LIMIT $4
`

type SyncMessagesParams struct {
	UserID         pgtype.UUID
	ConversationID pgtype.UUID
	AfterSequence  int64
	PageSize       int32
}

func (q *Queries) SyncMessages(ctx context.Context, arg SyncMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, syncMessages,
		arg.UserID,
		arg.ConversationID,
		arg.AfterSequence,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.ClientMessageID,
			&i.MessageSequence,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
