// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptContactRequest = `-- name: AcceptContactRequest :one
UPDATE contact_requests
SET status = 'accepted', updated_at = now()
WHERE id = $1
  AND recipient_id = $2
  AND status = 'pending'
RETURNING id, sender_id, recipient_id, status, created_at, updated_at
`

type AcceptContactRequestParams struct {
	ID          pgtype.UUID
	RecipientID pgtype.UUID
}

// use AcceptContactRequest and InsertContact in transaction
func (q *Queries) AcceptContactRequest(ctx context.Context, arg AcceptContactRequestParams) (ContactRequest, error) {
	row := q.db.QueryRow(ctx, acceptContactRequest, arg.ID, arg.RecipientID)
	var i ContactRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelContactRequest = `-- name: CancelContactRequest :one
UPDATE contact_requests
SET status = 'cancelled', updated_at = now()
WHERE id = $1
  AND sender_id = $2
  AND status = 'pending'
RETURNING id, sender_id, recipient_id, status, created_at, updated_at
`

type CancelContactRequestParams struct {
	ID       pgtype.UUID
	SenderID pgtype.UUID
}

func (q *Queries) CancelContactRequest(ctx context.Context, arg CancelContactRequestParams) (ContactRequest, error) {
	row := q.db.QueryRow(ctx, cancelContactRequest, arg.ID, arg.SenderID)
	var i ContactRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const declineContactRequest = `-- name: DeclineContactRequest :one
UPDATE contact_requests
SET status = 'declined', updated_at = now()
WHERE id = $1
  AND recipient_id = $2
  AND status = 'pending'
RETURNING id, sender_id, recipient_id, status, created_at, updated_at
`

type DeclineContactRequestParams struct {
	ID          pgtype.UUID
	RecipientID pgtype.UUID
}

func (q *Queries) DeclineContactRequest(ctx context.Context, arg DeclineContactRequestParams) (ContactRequest, error) {
	row := q.db.QueryRow(ctx, declineContactRequest, arg.ID, arg.RecipientID)
	var i ContactRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE user1_id = LEAST($1, $2)
  AND user2_id = GREATEST($1, $2)
`

type DeleteContactParams struct {
	User1ID   pgtype.UUID
	User1ID_2 pgtype.UUID
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.Exec(ctx, deleteContact, arg.User1ID, arg.User1ID_2)
	return err
}

const getContacts = `-- name: GetContacts :many
SELECT u.id, u.username, u.first_name, u.last_name
FROM contacts c
INNER JOIN users u
  ON u.id = CASE
    WHEN c.user1_id = $1 THEN c.user2_id
    ELSE c.user1_id
  END
WHERE user1_id = $1 OR user2_id = $1
`

type GetContactsRow struct {
	ID        pgtype.UUID
	Username  string
	FirstName string
	LastName  string
}

func (q *Queries) GetContacts(ctx context.Context, user1ID pgtype.UUID) ([]GetContactsRow, error) {
	rows, err := q.db.Query(ctx, getContacts, user1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactsRow
	for rows.Next() {
		var i GetContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertContact = `-- name: InsertContact :one
INSERT INTO contacts (user1_id, user2_id)
VALUES (
  LEAST($1, $2),
  GREATEST($1, $2)
)
RETURNING user1_id, user2_id, created_at
`

type InsertContactParams struct {
	Column1 interface{}
	Column2 interface{}
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, insertContact, arg.Column1, arg.Column2)
	var i Contact
	err := row.Scan(&i.User1ID, &i.User2ID, &i.CreatedAt)
	return i, err
}

const sendContactRequest = `-- name: SendContactRequest :one
INSERT INTO contact_requests (sender_id, recipient_id)
SELECT $1, id
FROM users
WHERE username = $2
RETURNING id, sender_id, recipient_id, status, created_at, updated_at
`

type SendContactRequestParams struct {
	SenderID pgtype.UUID
	Username string
}

func (q *Queries) SendContactRequest(ctx context.Context, arg SendContactRequestParams) (ContactRequest, error) {
	row := q.db.QueryRow(ctx, sendContactRequest, arg.SenderID, arg.Username)
	var i ContactRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
